# Site Settings
title: All Hands Active
subtitle: 255 E. Liberty St. Ste 225
author:
  name: All Hands Active
  email: board@allhandsactive.org
description: >-
  Ann Arbor's Maker Space! Offering tools, resources, classes,
  meet-ups, events, and workspace for makers and hackers in the
  A2 and Ypsi area.
baseurl: ''
url: 'https://allhandsactive.org'
repository: 'allhandsactive/site'

# Build settings
kramdown:
  input: GFM
exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'LICENSE', 'jekyll-remote-theme-*']
include: ["_pages", ".well-known"]
permalink: pretty


# Theme settings
remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: 'air'
title_separator: '|'
teaser: /assets/images/electronics-repair.jpg # fallback teaser, overridden in page yaml
logo: /assets/images/rhino.png

# Footer socials
footer:
  links:
    - label: "Meetup"
      icon: "fab fa-fw fa-meetup"
      url: "https://www.meetup.com/AllHandsActive/"
    - label: "Matrix Chat"
      url: "https://chat.allhandsactive.org"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/allhandsactivea2/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram icon-blackify"
      url: "https://www.instagram.com/allhandsactivea2/"
    - label: "Mastodon"
      icon: "fab fa-mastodon icon-blackify"
      url: "https://a2mi.social/@aha"
    - label: "Discord"
      icon: "fab fa-discord"
      url: "https://rhino.li/discord"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/allhandsactive/"



# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# set the proper timezone
timezone: America/Detroit

# simulate github pages
safe: true

# add key-value pair to pull GitHub Metadata
github: [metadata]
