# Site Settings
title: All Hands Active
subtitle: 255 E. Liberty St. Ste 225
author:
  name: All Hands Active
  email: board@allhandsactive.org
description: >-
  Ann Arbor's Maker Space! Offering tools, resources, classes,
  meet-ups, events, and workspace for makers and hackers in the
  A2 and Ypsi area.
baseurl: '/site'
url: 'https://tchell-aha.github.io'
repository: 'allhandsactive/site'


# Social media variables
twitter_username: AllHandsActive
facebook_username: AHA-All-Hands-Active-300100514925
meetup_username: allhandsactive
github_username:  allhandsactive


# Build settings
kramdown:
  input: GFM
exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'LICENSE']
include: ["_pages"]
permalink: pretty


# Theme settings
remote_theme: mmistakes/minimal-mistakes@4.19.0
minimal_mistakes_skin: 'contrast'
title_separator: '|'
teaser: /assets/images/electronics-repair.jpg # fallback teaser, overridden in page yaml
logo: /assets/images/rhino.png

# Footer socials
footer:
  links:
    - label: "Meetup"
      icon: "fab fa-fw fa-meetup"
      url: "https://www.meetup.com/AllHandsActive/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/allhandsactive"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/allhandsactivea2/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/allhandsactive/"


# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# set the proper timezone
timezone: America/Detroit

# simulate github pages
safe: true
